---
title: The Bookery
timezone: UTC
sass:
  style: compressed
collections:
  posts:
    title: Posts
    output: true
    comments: true
  uploads:
    title: Uploads
    output: true
  events:
    output: true
    permalink: /events/:path/
    title: Events
tagline: 'Dedicated to the creation, consumption, admiration, and discussion of literature.'
description: 'Dedicated to the creation, consumption, admiration, and discussion of literature. Striving to be the perfect home for all Bibliophiles, Bibliophages, Logophiles, and anyone who loves the written format, we provide a hub for tons of book-related content and conversations! We also host various events, such as the Read-a-Thon Weekend and Reading Wars.'
about: 'Dedicated to the creation, consumption, admiration, and discussion of literature. Striving to be the perfect home for all Bibliophiles, Bibliophages, Logophiles, and anyone who loves the written format, we provide a hub for tons of book-related content and conversations!'
baseurl: ''
url: https://bookerycommunity.com/
logo: 'https://bookerycommunity.com/assets/logo.png'
show_excerpts: true
instagram: 'https://www.instagram.com/midwaybookclub/'
twitter: ''
youtube: ''
header_pages:
- index.md
- calendar.md
theme: minima